title: Asif Hasan Zeshan
logo: /assets/img/headshot.png
description: Architect, Computational Design Researcher & Advocate for universally accessible public spaces
show_downloads: false
theme: jekyll-theme-tactile
